from enum import Enum


class CampaignStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    SOURCES_READY = "SOURCES_READY"
    GENERATING = "GENERATING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    PARTIALLY_APPROVED = "PARTIALLY_APPROVED"
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PARTIALLY_PUBLISHED = "PARTIALLY_PUBLISHED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AssetStatus(str, Enum):
    DRAFT = "DRAFT"
    QUALITY_CHECK = "QUALITY_CHECK"
    QUALITY_FAILED = "QUALITY_FAILED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
